version: "3.1"
services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db:/var/lib/mysql

  wp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-wordpress
    image: wp-custom
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: ww_
      WORDPRESS_DEBUG: 1
    ports:
      - 8080:80
    volumes:
      - ./wp:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/myphp.ini
      - ./.bashrc:/root/.bashrc

volumes:
  wp:
  db:
